import Head from "next/head";
import generatePDF, { Margin } from 'react-to-pdf';

const personalizacao = {
  // Baixar/Salvar = save / Abrir no navegador = open
  method: "open",
  page: {
    // Definir a margem: SMALL ou MEDIUM
    margin: Margin.MEDIUM,
    // Formato da página: A4 ou letter
    format: "A4",
    // Orientação do arquivo: portrait ou landscape
    orientation: "portrait",
  },
};

const recuperarConteudoParaPDF = () => document.getElementById("conteudo");

export default function Home() {
  return (
    <>
      <Head>
        <title>Celke</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button
          onClick={() => generatePDF(recuperarConteudoParaPDF, personalizacao)}
        >
          Gerar PDF
        </button>

        <div id="conteudo">
          <h1 style={{ textAlign: "center", color: "#f00", fontSize: "27px;" }}>
            Conteúdo do PDF
          </h1>
        </div>
      </main>
    </>
  );
}
